### ISSUE TITLE
From supply randomizer, be able to edit tile

### ISSUE THREAD

**Issue by loganmzz** [on3iro/aeons-end-randomizer#218]
**Is your feature request related to a problem? Please describe.**
It doesn't sound intuitive for me to use Settings in order to edit supply setups

**Describe the solution you'd like**
It would be nice to edit supply setups directly from randomizer section. Just add an "pen" icon and reuse form from settings. Then it would be nice to have "save as" capability in order to save edit. It also help to create an new supply from an existing one.

**Describe alternatives you've considered**
Just add a link to go to settings.

**Additional context**
None

**Comment by on3iro** [comment]
I get your point, but honestly this would mess with our UX concept quite a bit and would also mean we'd have to rework a lot of interal logic.
We want that all user based customization is centralized inside the settings with no additional ways to customize something. There should be one way to do something and one way only. Having too many options can quickly lead to even more confusion.

I see custom supply setups more as a power user feature and would therefore not want to convolute our randomizer UI. We might add links and additional tutorials/hints to the app, explaining how certain things are done in the future, though.

Thanks for the suggestion anyway :+1: - I am going to close this issue, because I doubt, that we will act on it.
