### ISSUE TITLE
Unable to select or deselect treasure promos

### ISSUE THREAD

**Issue by dyordanovv** [on3iro/aeons-end-randomizer#253]
In the current version (2.2.0) we are able to select only Promo Gems, the Treasures seems to be present in the promos.js file, but we cannot include them in the expedition and they never appear during the game

**Comment by on3iro** [comment]
@dyordanovv thanks for the feedback. I have to look into this, but if I remember correctly there is no treasure selection in version 2.2.0. The app simply uses all treasures from expansions you have selected.

However I am currently preparing a big update where the changes you suggest are already included. I'll keep you posted, as soon as it goes live (we should release it in the next two weeks). There is one feature which is not yet ready and we are currently testing and bugfixing it, because it changes and enhances expeditions quite a bit. It is basically preparation work for #232 ;)

**Comment by on3iro** [comment]
We just released v2.3.0 containing the feature you wished for @dyordanovv :)
