### ISSUE TITLE
Change language in settings tab

### ISSUE THREAD

**Issue by Gusti23** [on3iro/aeons-end-randomizer#342]
**Is your feature request related to a problem? Please describe.**
Right now we can change language inside particular expansion. Would it be possible to change all language of expansions at once.

**Describe the solution you'd like**
Put language changing tree in settings tab near to 'select all' that would apply for all of expansions.

**Describe alternatives you've considered**

**Additional context**
Also it would be nice if expansion titles in settings would be translated, because now there are in english and I remebered that I translated them into polish.

**Comment by on3iro** [comment]
@Gusti23

## Regarding an overall language switch

We decided to opt for a switch by expansion, because some users might only have certain translated content and might want to choose which language to use on an expansion base, so that it matches the content they actually own.

It might be possible to add an additional overall language switch, but I am afraid that this would make the UX harder to understand (what happens to expansions which have been manually set before the overall change, what happens to the "main" language switch if you change one or more expansions after all have been set to a certain language and so on). These are all questions we might be able to answer in the future. However I currently do not have the time to come up with a proper UX concept for this and it's not high on our list of priorities as well.

I will definitely keep this issue open, but please don't expect that we act upon it anytime soon.


## Regarding translated expansion names

Good catch. This is a bug and I will open another issue and fix this asap.

Thanks for your effort reporting this issue as well as making a reasonable feature request :) :+1:

**Comment by on3iro** [comment]
@Gusti23 fyi I just released v3.1.1 containing the fix for the expansion name issue :)

**Comment by on3iro** [comment]
## Notes

* [ ] Add select like the one inside each expansion to main expansions card
* [ ] when select is changed -> change languages for all expansions
* [ ] use selector to determine actual state of the select: if all expansions have the same language -> use that language key, if at least one expansion has a different language, show `custom` as currently selected option inside the main language select.

**Comment by Toorain** [comment]
> **Is your feature request related to a problem? Please describe.** Right now we can change language inside particular expansion. Would it be possible to change all language of expansions at once.
> 
> **Describe the solution you'd like** Put language changing tree in settings tab near to 'select all' that would apply for all of expansions.
> 
> **Describe alternatives you've considered**
> 
> **Additional context** Also it would be nice if expansion titles in settings would be translated, because now there are in english and I remebered that I translated them into polish.

I think you're right, there should be a way to select laguage in the settings, I've been searching for a good 5 minutes for the translated version, if you don't do a general language selector in the settings, please add a few lines to explain where to switch the language to be more user friendly.

**Comment by on3iro** [comment]
@Toorain thanks for the suggestion. I assume that something like a tool tip inside the main settings menu would suffice?
Are you interested in contributing and building something like this? :)
