### ISSUE TITLE
Expedition Import won't allow 'ANY' as valid supply tile type

### ISSUE THREAD

**Issue by Quicksav** [on3iro/aeons-end-randomizer#366]
**Describe the bug**
When importing an expedition, if the expedition has a supply tile with the type 'ANY' the importer throws an error. The code to handle the 'ANY' case is already in place, the validation message just needs to be removed so that the import can succeed.

**Screenshots**
![image](https://user-images.githubusercontent.com/43889574/94303132-31efee00-ff22-11ea-9695-844eacf69772.png)

**Comment by on3iro** [comment]
@Quicksav thanks for the bug report. There might be an issue with the json-schema. It might be enough to simply rebuild the schema _(src/components/pages/Expeditions/CreationDialog/ConfigImport/expeditionJsonSchema.ts)_

**Comment by Quicksav** [comment]
That was what I had meant, just explained it rather poorly. The schema was causing the validation error to be thrown, fixing the schema = removing the validation error (sorta). The above fix is exactly the one I used to get it working locally. 

If possible I'd like to try to create a pull request for this. I know its a simple issue that you could fix locally very easily but I'm trying to get used to working with Git still. From what I understand I want to create a local branch for the bug, then push it to the remote, then create a pull request for the branch I created into dev. Is that understanding correct?

**Comment by on3iro** [comment]
Awesome :)

Regarding the pull request:

1. You need to fork the repository on github (so you basically have your own version). This is necessary, because you are not a direct contributor listed in this repository (totally normal - usually only main contributors and maintainers have direct access to a repository)
2. Now you check out your fork locally
3. Create a feature branch (locally)
4. Make your fix
5. Commit
6. Push your feature branch to your remote (which is the fork)
7. Create a pull request:
  * iirc github will ask you, if you would like to create the PR agains the real repository instead of your fork -> do that and target our `dev` branch
  * that should do the trick
  * (haven't done a fork PR in a while - so these are just the steps out of my head ;) )

**Comment by on3iro** [comment]
@Quicksav  FYI: I just recently merged another feature which causes an additional error. However to actually properly fix this, I need to update our aer-types package and re-create the whole schema. It wouldn't make sense to fix this bug twice.
Therefore it would probably be better if you'd just tackle one of your other proposed issues :/ 
Sorry for the inconvenience!

**Comment by on3iro** [comment]
Closing this, because I fixed the issue with #369
